// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FormatComment
{
    internal sealed partial class Vsix
    {
        public const string Id = "FormatComment.8d0066e5-85d0-459e-a899-925c9da39b56";
        public const string Name = "FormatComment";
        public const string Description = @"格式化代码注释。";
        public const string Language = "zh-Hans";
        public const string Version = "1.0.4";
        public const string Author = "zxs";
        public const string Tags = "";
    }
}
