// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FormatComment
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FormatCommentString = "0fe50042-a94c-4212-aee9-7da8a4436ab8";
        public static Guid FormatComment = new Guid(FormatCommentString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FormatCommentGroup = 0x0001;
        public const int FormatCommentMenuGroup = 0x0002;
        public const int FormatCommentMenu = 0x0100;
        public const int FormatCommentLineTabRightCommand = 0x0101;
        public const int FormatCommentLineTabLeftCommand = 0x0102;
        public const int FormatCommentFuncToCCommand = 0x0103;
    }
}